export const fieldKey = {
  CATEGORY: "category",
  PLATFORM: "cloudPlatform",
  GEOGRAPHY: "geography",
  STORAGETYPE: "storageType",
  SIZE: "size",
  SESSIONSPERDAY: "sessionsPerDay",
  DAYSPERWEEK: "daysPerWeek",
  STORAGE: "estimatedStorage",
  SESSIONDURATION: "sessionDuration",
};

export const pricing = {
  Providers: {
    aws: {
      name: "AWS",
      geoLocations: {
        us_east_n_virginia: {
          displayName: "US East (Northern Virginia)",
          onDemand: 40,
          prePurchase: 23,
          Standard: 2,
          Enterprise: 3,
          BusinessCritical: 4,
        },
        us_east_ohio: {
          displayName: "US East (Ohio)",
          onDemand: 40,
          prePurchase: 23,
          Standard: 2,
          Enterprise: 3,
          BusinessCritical: 4,
        },
        us_west_oregon: {
          displayName: "US West (Oregon)",
          onDemand: 40,
          prePurchase: 23,
          Standard: 2,
          Enterprise: 3,
          BusinessCritical: 4,
        },
        canada_central: {
          displayName: "Canada (Central)",
          onDemand: 46,
          prePurchase: 25,
          Standard: 2.25,
          Enterprise: 3.5,
          BusinessCritical: 4.5,
        },
        eu_london: {
          displayName: "EU(London)",
          onDemand: 42,
          prePurchase: 24,
          Standard: 2.7,
          Enterprise: 4,
          BusinessCritical: 5.4,
        },
        eu_ireland: {
          displayName: "EU(Ireland)",
          onDemand: 40,
          prePurchase: 23,
          Standard: 2.6,
          Enterprise: 3.9,
          BusinessCritical: 5.2,
        },
        eu_frankfurt: {
          displayName: "EU(Frankfurt)",
          onDemand: 45,
          prePurchase: 24.5,
          Standard: 2.6,
          Enterprise: 3.9,
          BusinessCritical: 5.2,
        },
        europe_stockholm: {
          displayName: "Europe (Stockholm)",
          onDemand: 40,
          prePurchase: 23,
          Standard: 2.6,
          Enterprise: 3.9,
          BusinessCritical: 5.2,
        },
        apac_sydney: {
          displayName: "Asia Pacific (Sydney)",
          onDemand: 46,
          prePurchase: 25,
          Standard: 2.75,
          Enterprise: 4.05,
          BusinessCritical: 5.5,
        },
        apac_singapore: {
          displayName: "Asia Pacific (Singapore)",
          onDemand: 46,
          prePurchase: 25,
          Standard: 2.5,
          Enterprise: 3.7,
          BusinessCritical: 5.0,
        },
        apac_tokyo: {
          displayName: "Asia Pacific (Tokyo)",
          onDemand: 46,
          prePurchase: 25,
          Standard: 2.85,
          Enterprise: 4.3,
          BusinessCritical: 5.7,
        },
        apac_seoul: {
          displayName: "Asia Pacific (Seoul)",
          onDemand: 46,
          prePurchase: 25,
          Standard: 2.75,
          Enterprise: 4.05,
          BusinessCritical: 5.5,
        },
        apac_mumbai: {
          displayName: "Asia Pacific (Mumbai)",
          onDemand: 46,
          prePurchase: 25,
          Standard: 2.2,
          Enterprise: 3.3,
          BusinessCritical: 4.4,
        },
      },
    },
    azure: {
      name: "Microsoft Azure",
      geoLocations: {
        east_us_virginia: {
          displayName: "East US 2 (Virginia)",
          onDemand: 40,
          capacity: 23,
          Standard: 2,
          Enterprise: 3,
          BusinessCritical: 4,
        },
        west_us_washington: {
          displayName: "West US 2 (Washington)",
          onDemand: 40,
          capacity: 23,
          Standard: 2,
          Enterprise: 3,
          BusinessCritical: 4,
        },
        central_us_iowa: {
          displayName: "Central US (Iowa)",
          onDemand: 40,
          capacity: 23,
          Standard: 2,
          Enterprise: 3,
          BusinessCritical: 4,
        },
        canada_central_toronto: {
          displayName: "Canada Central (Toronto)",
          onDemand: 46,
          capacity: 25,
          Standard: 2.25,
          Enterprise: 3.5,
          BusinessCritical: 4.5,
        },
        west_europe_netherlands: {
          displayName: "West Europe (Netherlands)",
          onDemand: 40,
          capacity: 23,
          Standard: 2.6,
          Enterprise: 3.9,
          BusinessCritical: 5.2,
        },
        north_europe_ireland: {
          displayName: "North Europe (Ireland)",
          onDemand: 40,
          capacity: 23,
          Standard: 2.6,
          Enterprise: 3.9,
          BusinessCritical: 5.2,
        },
        australia_east_sydney: {
          displayName: "Australia East (Sydney)",
          onDemand: 46,
          capacity: 25,
          Standard: 2.75,
          Enterprise: 4.05,
          BusinessCritical: 5.5,
        },
        southeast_asia_singapore: {
          displayName: "Southeast Asia (Singapore)",
          onDemand: 46,
          capacity: 25,
          Standard: 2.5,
          Enterprise: 3.7,
          BusinessCritical: 5,
        },
        switzerland_north_zurich: {
          displayName: "Switzerland North (Zurich)",
          onDemand: 50.5,
          capacity: 28.8,
          Standard: 3.1,
          Enterprise: 4.65,
          BusinessCritical: 6.2,
        },
        japan_east_tokyo: {
          displayName: "Japan East (Tokyo)",
          onDemand: 46,
          capacity: 25,
          Standard: 2.85,
          Enterprise: 4.3,
          BusinessCritical: 5.7,
        },
        uae_north_dubai: {
          displayName: "UAE North (Dubai)",
          onDemand: 44.5,
          capacity: 25.4,
          Standard: 2.7,
          Enterprise: 4.4,
          BusinessCritical: 5.4,
        },
      },
    },
    gcp: {
      name: "Google Cloud Platform",
      geoLocations: {
        us_central_iowa: {
          displayName: "us-central1 (Iowa)",
          onDemand: 35,
          capacity: 20,
          Standard: 2,
          Enterprise: 3,
          BusinessCritical: 4,
        },
        europe_west2_london: {
          displayName: "europe-west2 (London)",
          onDemand: 40,
          capacity: 23,
          Standard: 2.7,
          Enterprise: 4,
          BusinessCritical: 5.4,
        },
        europe_west4_netherlands: {
          displayName: "europe-west4 (Netherlands)",
          onDemand: 35,
          capacity: 20,
          Standard: 2.6,
          Enterprise: 3.9,
          BusinessCritical: 5.2,
        },
      },
    },
  },
  Credits: {
    XS: 1,
    S: 2,
    M: 4,
    L: 8,
    XL: 16,
    "2XL": 32,
    "3XL": 64,
    "4XL": 128,
  },
};

export const fields = [
  {
    label: "Category of Application",
    key: fieldKey.CATEGORY,
    type: 1,
    values: [
      { value: "Standard", name: "Standard" },
      { value: "Enterprise", name: "Enterprise" },
      { value: "BusinessCritical", name: "Business Critical" },
    ],
  },
  {
    label: "Cloud Platform",
    key: fieldKey.PLATFORM,
    type: 1,
    values: [
      { value: "aws", name: "AWS" },
      { value: "azure", name: "Microsoft Azure" },
      { value: "gcp", name: "Google Cloud" },
    ],
  },
  {
    label: "Geography",
    key: fieldKey.GEOGRAPHY,
    type: 1,
    values: [
      { value: "us_east_n_virginia", name: "US East (Northern Virginia)" },
      { value: "us_east_ohio", name: "US East (Ohio)" },
      { value: "us_west_oregon", name: "US West (Oregon)" },
      { value: "canada_central", name: "Canada (Central)" },
      { value: "eu_london", name: "EU(London)" },
      { value: "eu_ireland", name: "EU(Ireland)" },
      { value: "eu_frankfurt", name: "EU(Frankfurt)" },
      { value: "europe_stockholm", name: "Europe (Stockholm)" },
      { value: "apac_sydney", name: "Asia Pacific (Sydney)" },
      { value: "apac_singapore", name: "Asia Pacific (Singapore)" },
      { value: "apac_tokyo", name: "Asia Pacific (Tokyo)" },
      { value: "apac_seoul", name: "Asia Pacific (Seoul)" },
      { value: "apac_mumbai", name: "Asia Pacific (Mumbai)" },
      { value: "east_us_virginia", name: "East US 2 (Virginia)" },
      { value: "west_us_washington", name: "West US 2 (Washington)" },
      { value: "central_us_iowa", name: "Central US (Iowa)" },
      { value: "canada_central_toronto", name: "Canada Central (Toronto)" },
      { value: "west_europe_netherlands", name: "West Europe (Netherlands)" },
      { value: "north_europe_ireland", name: "North Europe (Ireland)" },
      { value: "australia_east_sydney", name: "Australia East (Sydney)" },
      { value: "southeast_asia_singapore", name: "Southeast Asia (Singapore)" },
      { value: "switzerland_north_zurich", name: "Switzerland North (Zurich)" },
      { value: "japan_east_tokyo", name: "Japan East (Tokyo)" },
      { value: "uae_north_dubai", name: "UAE North (Dubai)" },
      { value: "us_central_iowa", name: "us-central1 (Iowa)" },
      { value: "europe_west2_london", name: "europe-west2 (London)" },
      { value: "europe_west4_netherlands", name: "europe-west4 (Netherlands)" },
    ],
  },
  {
    label: "Type of storage",
    key: fieldKey.STORAGETYPE,
    type: 1,
    values: [
      { value: "onDemand", name: "On Demand" },
      { value: "prePurchase", name: "PrePurchase" },
    ],
  },
  {
    label: "Size of warehouse",
    key: fieldKey.SIZE,
    type: 1,
    values: [
      { value: "XS", name: "XS" },
      { value: "S", name: "S" },
      { value: "M", name: "M" },
      { value: "L", name: "L" },
      { value: "XL", name: "XL" },
      { value: "2XL", name: "2XL" },
      { value: "3XL", name: "3XL" },
      { value: "4XL", name: "4XL" },
    ],
  },
  {
    label: "No. of Sessions per day",
    key: fieldKey.SESSIONSPERDAY,
    type: 2,
    step: 1,
    min: 1,
    max: 24,
  },
  {
    label: "No. of days of week",
    key: fieldKey.DAYSPERWEEK,
    type: 2,
    step: 1,
    min: 1,
    max: 7,
  },
  {
    label: "Est. storage per month ",
    key: fieldKey.STORAGE,
    type: 2,
    step: 10,
    min: 10,
    max: 1024,
  },
  {
    label: "Duration of each session",
    key: fieldKey.SESSIONDURATION,
    type: 2,
    step: 1,
    min: 1,
    max: 12,
  },
];

export default { pricing, fieldKey, fields };
